// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System.Xml.Serialization;

#pragma warning disable 1573, 1591
#nullable enable

namespace Server
{
	[Table("city_info")]
	public class CityInfo
	{
		[Column("info_id"     , IsPrimaryKey = true, IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)] public long?   InfoId      { get; set; } // INTEGER
		[Column("city_id"                                                                                       )] public long    CityId      { get; set; } // INTEGER
		[Column("founded_year"                                                                                  )] public long?   FoundedYear { get; set; } // INTEGER
		[Column("area_km2"                                                                                      )] public double? AreaKm2     { get; set; } // REAL
		[Column("elevation_m"                                                                                   )] public long?   ElevationM  { get; set; } // INTEGER
		[Column("timezone"                                                                                      )] public string? Timezone    { get; set; } // TEXT
		[Column("postal_code"                                                                                   )] public string? PostalCode  { get; set; } // TEXT
		[Column("website"                                                                                       )] public string? Website     { get; set; } // TEXT
		[Column("description"                                                                                   )] public string? Description { get; set; } // TEXT

		#region Associations
		/// <summary>
		/// FK_city_info_0
		/// </summary>
		[Association(CanBeNull = false, ThisKey = nameof(CityId), OtherKey = nameof(Server.City.CityId))]
		[XmlIgnore]
		public City City { get; set; } = null!;
		#endregion
	}
}
