// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System.Collections.Generic;

#pragma warning disable 1573, 1591
#nullable enable

namespace Server
{
	[Table("cities")]
	public class City
	{
		[Column("city_id"          , IsPrimaryKey = true , IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)] public long?   CityId           { get; set; } // INTEGER
		[Column("city"             , CanBeNull    = false                                                             )] public string  City1            { get; set; } = null!; // TEXT
		[Column("lat"                                                                                                 )] public double? Lat              { get; set; } // REAL
		[Column("lng"                                                                                                 )] public double? Lng              { get; set; } // REAL
		[Column("country"                                                                                             )] public string? Country          { get; set; } // TEXT
		[Column("iso2"                                                                                                )] public string? Iso2             { get; set; } // TEXT
		[Column("admin_name"                                                                                          )] public string? AdminName        { get; set; } // TEXT
		[Column("capital"                                                                                             )] public string? Capital          { get; set; } // TEXT
		[Column("population"                                                                                          )] public long?   Population       { get; set; } // INTEGER
		[Column("population_proper"                                                                                   )] public long?   PopulationProper { get; set; } // INTEGER

		#region Associations
		/// <summary>
		/// FK_city_info_0 backreference
		/// </summary>
		[Association(ThisKey = nameof(CityId), OtherKey = nameof(CityInfo.CityId))]
		public List<CityInfo> CityInfos { get; set; } = null!;
		#endregion
	}
}
