// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB;
using LinqToDB.Async;
using LinqToDB.Data;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;

#pragma warning disable 1573, 1591
#nullable enable

namespace Server
{
	public partial class MyDb : DataConnection
	{
		public MyDb()
		{
			InitDataContext();
		}

		public MyDb(string configuration)
			: base(new DataOptions().UseSQLite(configuration))
		{
			InitDataContext();
		}

		public MyDb(DataOptions<MyDb> options)
			: base(options.Options)
		{
			InitDataContext();
		}

		partial void InitDataContext();

		public ITable<City>     Cities    => this.GetTable<City>();
		public ITable<CityInfo> CityInfos => this.GetTable<CityInfo>();
	}

	public static partial class ExtensionMethods
	{
		#region Table Extensions
		public static City? Find(this ITable<City> table, long? cityId)
		{
			return table.FirstOrDefault(e => e.CityId == cityId);
		}

		public static Task<City?> FindAsync(this ITable<City> table, long? cityId, CancellationToken cancellationToken = default)
		{
			return table.FirstOrDefaultAsync(e => e.CityId == cityId, cancellationToken);
		}

		public static CityInfo? Find(this ITable<CityInfo> table, long? infoId)
		{
			return table.FirstOrDefault(e => e.InfoId == infoId);
		}

		public static Task<CityInfo?> FindAsync(this ITable<CityInfo> table, long? infoId, CancellationToken cancellationToken = default)
		{
			return table.FirstOrDefaultAsync(e => e.InfoId == infoId, cancellationToken);
		}
		#endregion
	}
}
