// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System.Collections.Generic;

#pragma warning disable 1573, 1591
#nullable enable

namespace DataModel
{
	[Table("MediaType")]
	public class MediaType
	{
		[Column("ID"  , IsPrimaryKey = true, IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)] public long    Id   { get; set; } // integer
		[Column("Name"                                                                                  )] public string? Name { get; set; } // varchar(50)

		#region Associations
		/// <summary>
		/// FK_Media_0_0 backreference
		/// </summary>
		[Association(ThisKey = nameof(Id), OtherKey = nameof(Medium.MediaType))]
		public IEnumerable<Medium> Media { get; set; } = null!;
		#endregion
	}
}
