// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;

#pragma warning disable 1573, 1591
#nullable enable

namespace DataModel
{
	[Table("Media")]
	public class Medium
	{
		[Column("id"       , IsPrimaryKey = true, IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)] public long    Id        { get; set; } // integer
		[Column("Title"                                                                                      )] public string? Title     { get; set; } // varchar(20)
		[Column("Year"                                                                                       )] public int?    Year      { get; set; } // int
		[Column("MediaType"                                                                                  )] public int?    MediaType { get; set; } // int
		[Column("Publisher"                                                                                  )] public string? Publisher { get; set; } // varchar(100)
		[Column("Image"                                                                                      )] public string? Image     { get; set; } // varchar(100)

		#region Associations
		/// <summary>
		/// FK_Media_0_0
		/// </summary>
		[Association(ThisKey = nameof(MediaType), OtherKey = nameof(DataModel.MediaType.Id))]
		public MediaType? FkMedia00 { get; set; }
		#endregion
	}
}
