// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;

#pragma warning disable 1573, 1591
#nullable enable

namespace DataModel
{
	[Table("Bilder")]
	public class Bilder
	{
		[Column("id"    , IsPrimaryKey = true)] public long     Id     { get; set; } // integer
		[Column("name"                       )] public string?  Name   { get; set; } // text(max)
		[Column("wonder"                     )] public decimal? Wonder { get; set; } // numeric
	}
}
