// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;

#pragma warning disable 1573, 1591
#nullable enable

namespace Server.Models;

[Table("worldcities")]
public class Worldcity
{
	[Column("ogc_fid"   , IsPrimaryKey = true, IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)] public long?   OgcFid     { get; set; } // INTEGER
	[Column("GEOMETRY"                                                                                    )] public byte[]? Geometry   { get; set; } // BLOB
	[Column("city"                                                                                        )] public string? City       { get; set; } // VARCHAR
	[Column("city_ascii"                                                                                  )] public string? CityAscii  { get; set; } // VARCHAR
	[Column("lat"                                                                                         )] public double? Lat        { get; set; } // FLOAT
	[Column("lng"                                                                                         )] public double? Lng        { get; set; } // FLOAT
	[Column("country"                                                                                     )] public string? Country    { get; set; } // VARCHAR
	[Column("iso2"                                                                                        )] public string? Iso2       { get; set; } // VARCHAR
	[Column("iso3"                                                                                        )] public string? Iso3       { get; set; } // VARCHAR
	[Column("admin_name"                                                                                  )] public string? AdminName  { get; set; } // VARCHAR
	[Column("capital"                                                                                     )] public string? Capital    { get; set; } // VARCHAR
	[Column("population"                                                                                  )] public string? Population { get; set; } // VARCHAR
	[Column("id"                                                                                          )] public string? Id         { get; set; } // VARCHAR
}
