// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System.Collections.Generic;

#pragma warning disable 1573, 1591
#nullable enable

namespace DataModel
{
	[Table("chat")]
	public class Chat
	{
		[Column("chat_id", IsPrimaryKey = true, IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)] public long    ChatId  { get; set; } // integer
		[Column("user_id"                                                                                  )] public long?   UserId  { get; set; } // integer
		[Column("content"                                                                                  )] public string? Content { get; set; } // text(max)

		#region Associations
		/// <summary>
		/// FK_chat_0_0
		/// </summary>
		[Association(ThisKey = nameof(UserId), OtherKey = nameof(DataModel.User.UserId))]
		public User? User { get; set; }

		/// <summary>
		/// FK_room_chat_0_0 backreference
		/// </summary>
		[Association(ThisKey = nameof(ChatId), OtherKey = nameof(RoomChat.ChatId))]
		public IEnumerable<RoomChat> RoomChats { get; set; } = null!;
		#endregion
	}
}
