// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;

#pragma warning disable 1573, 1591
#nullable enable

namespace DataModel
{
	[Table("room_user")]
	public class RoomUser
	{
		[Column("user_id", IsPrimaryKey = true, PrimaryKeyOrder = 0)] public long UserId { get; set; } // integer
		[Column("room_id", IsPrimaryKey = true, PrimaryKeyOrder = 1)] public long RoomId { get; set; } // integer

		#region Associations
		/// <summary>
		/// FK_room_user_0_0
		/// </summary>
		[Association(CanBeNull = false, ThisKey = nameof(RoomId), OtherKey = nameof(Room.RoomId))]
		public Room Roomuser { get; set; } = null!;

		/// <summary>
		/// FK_room_user_1_0
		/// </summary>
		[Association(CanBeNull = false, ThisKey = nameof(UserId), OtherKey = nameof(User.UserId))]
		public User Roomuser1 { get; set; } = null!;
		#endregion
	}
}
