// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System.Collections.Generic;

#pragma warning disable 1573, 1591
#nullable enable

namespace DataModel
{
	[Table("room")]
	public class Room
	{
		[Column("room_id", IsPrimaryKey = true, IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)] public long    RoomId { get; set; } // integer
		[Column("name"                                                                                     )] public string? Name   { get; set; } // varchar(50)

		#region Associations
		/// <summary>
		/// FK_room_chat_1_0 backreference
		/// </summary>
		[Association(ThisKey = nameof(RoomId), OtherKey = nameof(RoomChat.RoomId))]
		public IEnumerable<RoomChat> RoomChats { get; set; } = null!;

		/// <summary>
		/// FK_room_user_0_0 backreference
		/// </summary>
		[Association(ThisKey = nameof(RoomId), OtherKey = nameof(RoomUser.RoomId))]
		public IEnumerable<RoomUser> RoomUsers { get; set; } = null!;
		#endregion
	}
}
