// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System.Collections.Generic;

#pragma warning disable 1573, 1591
#nullable enable

namespace DataModel
{
	[Table("users")]
	public class User
	{
		[Column("user_id"  , IsPrimaryKey = true, IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)] public long    UserId    { get; set; } // integer
		[Column("name"                                                                                       )] public string? Name      { get; set; } // varchar(50)
		[Column("ipaddress"                                                                                  )] public string? Ipaddress { get; set; } // varchar(50)
		[Column("password"                                                                                   )] public string? Password  { get; set; } // varchar(50)

		#region Associations
		/// <summary>
		/// FK_chat_0_0 backreference
		/// </summary>
		[Association(ThisKey = nameof(UserId), OtherKey = nameof(Chat.UserId))]
		public IEnumerable<Chat> Chats { get; set; } = null!;

		/// <summary>
		/// FK_room_user_1_0 backreference
		/// </summary>
		[Association(ThisKey = nameof(UserId), OtherKey = nameof(RoomUser.UserId))]
		public IEnumerable<RoomUser> RoomUsers { get; set; } = null!;
		#endregion
	}
}
