// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;
using System.Xml.Serialization;

#pragma warning disable 1573, 1591
#nullable enable

namespace DataModel
{
	[XmlRoot]
	[Table("ChatMessages")]
	public class ChatMessage
	{
		public ChatMessage() { }

		[Column("Id", IsPrimaryKey = true, IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)] public long Id { get; set; } // integer
		[Column("UserId")] public long UserId { get; set; } // integer
		[Column("ChatRoomId")] public long? ChatRoomId { get; set; } // integer
		[Column("PrivateToUserId")] public long? PrivateToUserId { get; set; } // integer
		[Column("Content", CanBeNull = false)] public string Content { get; set; } = null!; // text(max)
		[Column("Timestamp")] public DateTime Timestamp { get; set; } // datetime

		#region Associations
		/// <summary>
		/// FK_ChatMessages_0_0
		/// </summary>
		[Association(ThisKey = nameof(PrivateToUserId), OtherKey = nameof(DataModel.User.Id))]
		[XmlIgnore]
		public User? PrivateToUser { get; set; }

		/// <summary>
		/// FK_ChatMessages_1_0
		/// </summary>
		[Association(ThisKey = nameof(ChatRoomId), OtherKey = nameof(DataModel.ChatRoom.Id))]
		[XmlIgnore]
		public ChatRoom? ChatRoom { get; set; }

		/// <summary>
		/// FK_ChatMessages_2_0
		/// </summary>
		[Association(CanBeNull = false, ThisKey = nameof(UserId), OtherKey = nameof(DataModel.User.Id))]
		[XmlIgnore]
		public User User { get; set; } = null!;
		#endregion
	}
}
