// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;
using System.Collections.Generic;
using System.Xml.Serialization;

#pragma warning disable 1573, 1591
#nullable enable

namespace DataModel
{
	[Table("ChatRooms")]
	[XmlRoot]
	public class ChatRoom
	{
		public ChatRoom() { }

		[Column("Id", IsPrimaryKey = true, IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)] public long Id { get; set; } // integer
		[Column("Name", CanBeNull = false)] public string Name { get; set; } = null!; // text(max)
		[Column("Description", CanBeNull = false)] public string Description { get; set; } = null!; // text(max)
		[Column("Created")] public DateTime Created { get; set; } // datetime

		#region Associations
		/// <summary>
		/// FK_ChatMessages_1_0 backreference
		/// </summary>
		[Association(ThisKey = nameof(Id), OtherKey = nameof(ChatMessage.ChatRoomId))]
		[XmlIgnore]
		public IEnumerable<ChatMessage> ChatMessages { get; set; } = null!;

		/// <summary>
		/// FK_RoomMembers_0_0 backreference
		/// </summary>
		[Association(ThisKey = nameof(Id), OtherKey = nameof(RoomMember.RoomId))]
		[XmlIgnore]
		public IEnumerable<RoomMember> RoomMembers { get; set; } = null!;
		#endregion
	}
}
