// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;
using System.Xml.Serialization;

#pragma warning disable 1573, 1591
#nullable enable

namespace DataModel
{
	[Table("RoomMembers")]
	[XmlRoot]
	public class RoomMember
	{
		public RoomMember() { }

		[Column("UserId", IsPrimaryKey = true, PrimaryKeyOrder = 0)] public long UserId { get; set; } // integer
		[Column("RoomId", IsPrimaryKey = true, PrimaryKeyOrder = 1)] public long RoomId { get; set; } // integer
		[Column("JoinedAt")] public DateTime JoinedAt { get; set; } // datetime

		#region Associations
		/// <summary>
		/// FK_RoomMembers_0_0
		/// </summary>
		[Association(CanBeNull = false, ThisKey = nameof(RoomId), OtherKey = nameof(ChatRoom.Id))]
		[XmlIgnore]
		public ChatRoom FkRoomMembers00 { get; set; } = null!;

		/// <summary>
		/// FK_RoomMembers_1_0
		/// </summary>
		[Association(CanBeNull = false, ThisKey = nameof(UserId), OtherKey = nameof(User.Id))]
		[XmlIgnore]
		public User FkRoomMembers10 { get; set; } = null!;
		#endregion
	}
}
