// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;
using System.Collections.Generic;
using System.Xml.Serialization;

#pragma warning disable 1573, 1591
#nullable enable

namespace DataModel
{
	[Table("Users")]
	[XmlRoot]
	public class User
	{
		public User() { }

		[Column("Id", IsPrimaryKey = true, IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)] public long Id { get; set; } // integer
		[Column("Username", CanBeNull = false)] public string Username { get; set; } = null!; // text(max)
		[Column("PasswordHash", CanBeNull = false)] public string PasswordHash { get; set; } = null!; // text(max)
		[Column("Color", CanBeNull = false)] public string Color { get; set; } = null!; // text(max)
		[Column("ProfileImageBase64")] public string? ProfileImageBase64 { get; set; } // text(max)
		[Column("LastSeen")] public DateTime LastSeen { get; set; } // datetime

		#region Associations
		/// <summary>
		/// FK_ChatMessages_0_0 backreference
		/// </summary>
		[Association(ThisKey = nameof(Id), OtherKey = nameof(ChatMessage.PrivateToUserId))]
		[XmlIgnore]
		public IEnumerable<ChatMessage> ChatMessages { get; set; } = null!;

		/// <summary>
		/// FK_ChatMessages_2_0 backreference
		/// </summary>
		[Association(ThisKey = nameof(Id), OtherKey = nameof(ChatMessage.UserId))]
		[XmlIgnore]
		public IEnumerable<ChatMessage> ChatMessages1 { get; set; } = null!;

		/// <summary>
		/// FK_RoomMembers_1_0 backreference
		/// </summary>
		[Association(ThisKey = nameof(Id), OtherKey = nameof(RoomMember.UserId))]
		[XmlIgnore]
		public IEnumerable<RoomMember> RoomMembers { get; set; } = null!;
		#endregion
	}
}
