#ifndef _QX_FLUGPLANER_EXPORT_H_
#define _QX_FLUGPLANER_EXPORT_H_

#ifdef _BUILDING_QX_FLUGPLANER
#define QX_FLUGPLANER_DLL_EXPORT QX_DLL_EXPORT_HELPER
#else // _BUILDING_QX_FLUGPLANER
#define QX_FLUGPLANER_DLL_EXPORT QX_DLL_IMPORT_HELPER
#endif // _BUILDING_QX_FLUGPLANER

#ifdef _BUILDING_QX_FLUGPLANER
#define QX_REGISTER_HPP_QX_FLUGPLANER     QX_REGISTER_HPP_EXPORT_DLL
#define QX_REGISTER_CPP_QX_FLUGPLANER     QX_REGISTER_CPP_EXPORT_DLL
#else // _BUILDING_QX_FLUGPLANER
#define QX_REGISTER_HPP_QX_FLUGPLANER     QX_REGISTER_HPP_IMPORT_DLL
#define QX_REGISTER_CPP_QX_FLUGPLANER     QX_REGISTER_CPP_IMPORT_DLL
#endif // _BUILDING_QX_FLUGPLANER

#endif // _QX_FLUGPLANER_EXPORT_H_
