// ---------------------------------------------------------------------------------------------------
// <auto-generated>

using System.Collections.Generic;

#pragma warning disable 1573, 1591
#nullable enable

namespace Server
{
	public class City
	{
		public long?   CityId           { get; set; } // INTEGER
		public string  City1            { get; set; } = null!; // TEXT
		public double? Lat              { get; set; } // REAL
		public double? Lng              { get; set; } // REAL
		public string? Country          { get; set; } // TEXT
		public string? Iso2             { get; set; } // TEXT
		public string? AdminName        { get; set; } // TEXT
		public string? Capital          { get; set; } // TEXT
		public long?   Population       { get; set; } // INTEGER
		public long?   PopulationProper { get; set; } // INTEGER

		public List<CityInfo> CityInfos { get; set; } = null!;
	}
}
